2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Configure stats pid to 21055
2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from /home/jo/.config/wandb/settings
2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from /home/jo/code/kaggle/wandb/settings
2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-01-08 13:04:01,028 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_init.py:_log_setup():524] Logging user logs to /home/jo/code/kaggle/wandb/run-20240108_130401-x8yye6h6/logs/debug.log
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_init.py:_log_setup():525] Logging internal logs to /home/jo/code/kaggle/wandb/run-20240108_130401-x8yye6h6/logs/debug-internal.log
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_init.py:init():564] calling init triggers
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'momentum': 0.9, 'epochs': 5, 'loss_function': <keras.src.losses.BinaryCrossentropy object at 0x7f61487cc1c0>, 'architecture': 'MLP'}
2024-01-08 13:04:01,029 INFO    MainThread:21055 [wandb_init.py:init():589] re-initializing run, found existing run on stack: vxukstqt
2024-01-08 13:04:01,031 INFO    MainThread:21055 [wandb_run.py:_finish():1962] finishing run jcrone/Titanic/vxukstqt
2024-01-08 13:04:01,032 ERROR   MainThread:21055 [jupyter.py:save_history():437] Run pip install nbformat to save notebook history
2024-01-08 13:04:01,032 INFO    MainThread:21055 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-08 13:04:01,032 INFO    MainThread:21055 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-01-08 13:04:01,032 INFO    MainThread:21055 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-08 13:04:01,032 INFO    MainThread:21055 [wandb_run.py:_restore():2185] restore
2024-01-08 13:04:01,032 INFO    MainThread:21055 [wandb_run.py:_restore():2191] restore done
2024-01-08 13:04:05,623 INFO    MainThread:21055 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-08 13:04:05,624 INFO    MainThread:21055 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-08 13:04:05,628 INFO    MainThread:21055 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-01-08 13:04:05,699 INFO    MainThread:21055 [wandb_init.py:init():614] starting backend
2024-01-08 13:04:05,699 INFO    MainThread:21055 [wandb_init.py:init():618] setting up manager
2024-01-08 13:04:05,701 INFO    MainThread:21055 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-01-08 13:04:05,702 INFO    MainThread:21055 [wandb_init.py:init():624] backend started and connected
2024-01-08 13:04:05,711 INFO    MainThread:21055 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-08 13:04:05,711 INFO    MainThread:21055 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-08 13:04:05,711 INFO    MainThread:21055 [wandb_init.py:init():716] updated telemetry
2024-01-08 13:04:05,715 INFO    MainThread:21055 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-08 13:04:07,307 INFO    MainThread:21055 [wandb_run.py:_on_init():2254] communicating current version
2024-01-08 13:04:07,455 INFO    MainThread:21055 [wandb_run.py:_on_init():2263] got version response 
2024-01-08 13:04:07,455 INFO    MainThread:21055 [wandb_init.py:init():800] starting run threads in backend
2024-01-08 13:04:07,503 INFO    MainThread:21055 [wandb_run.py:_console_start():2233] atexit reg
2024-01-08 13:04:07,504 INFO    MainThread:21055 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-08 13:04:07,504 INFO    MainThread:21055 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-08 13:04:07,504 INFO    MainThread:21055 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-08 13:04:07,505 INFO    MainThread:21055 [wandb_init.py:init():841] run started, returning control to user process
2024-01-08 13:04:24,330 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Configure stats pid to 21055
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from /home/jo/.config/wandb/settings
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from /home/jo/code/kaggle/wandb/settings
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'api_key': '***REDACTED***'}
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:_log_setup():524] Logging user logs to /home/jo/code/kaggle/wandb/run-20240108_130424-wxa5ruo8/logs/debug.log
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:_log_setup():525] Logging internal logs to /home/jo/code/kaggle/wandb/run-20240108_130424-wxa5ruo8/logs/debug-internal.log
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f61503df4f0>
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:init():564] calling init triggers
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.005, 'momentum': 0.9, 'epochs': 5, 'loss_function': <keras.src.losses.BinaryCrossentropy object at 0x7f61503de200>, 'architecture': 'MLP'}
2024-01-08 13:04:24,331 INFO    MainThread:21055 [wandb_init.py:init():589] re-initializing run, found existing run on stack: x8yye6h6
2024-01-08 13:04:24,333 INFO    MainThread:21055 [wandb_run.py:_finish():1962] finishing run jcrone/Titanic/x8yye6h6
2024-01-08 13:04:24,333 INFO    MainThread:21055 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-08 13:04:24,334 INFO    MainThread:21055 [wandb_run.py:_restore():2185] restore
2024-01-08 13:04:24,334 INFO    MainThread:21055 [wandb_run.py:_restore():2191] restore done
2024-01-08 13:04:28,769 INFO    MainThread:21055 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-08 13:04:28,769 INFO    MainThread:21055 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-08 13:04:28,772 INFO    MainThread:21055 [wandb_run.py:_footer_sync_info():3796] logging synced files
